Started: functions over processes

diff --git a/bin/gui_setup b/bin/gui_setup
--- a/bin/gui_setup
+++ b/bin/gui_setup
@@ -11,6 +11,31 @@ DB_FILE="${THIS_TMP}/db.desktop.db"
 TMP_DB_FILE="/tmp/gui_setup.db.desktop.db"
 shift
 
+
+app_name_to_win_id () {
+  local app_name=$1
+  shift
+  normal_window_info |  grep --extended-regexp -i '^[^[:space:]]+[[:space:]]'$app_name'[[:space:]]'  | cut -f1 | tail -n 1 || :
+}
+
+normal_window_info () {
+    info="$(wmctrl -lp | tr -s ' ')"
+    win_ids="$(echo -e "$info" | cut -d' ' -f1)"
+    types="$(echo -e "$win_ids" | xargs -I ID xprop -id ID _NET_WM_WINDOW_TYPE  | cut -d'=' -f2- | tr -d ' ')"
+    pids="$(echo -e "$info" | cut -d' ' -f3)"
+    titles="$(echo -e "$info" | cut -d' ' -f5-)"
+
+    full="$(paste <(echo -e "$types") <(echo -e "$win_ids") <(echo -e "$pids") <(echo -e "$titles"))"
+
+    # We first HAVE TO filter out non-normal windows, THEN get the PID/COMM info.
+    # This is because sometimes the pid of window is listed as "0". I don't know why.
+    #  A pid of "0" will lead "ps" to give us an out-of-range error.
+    normal="$(echo -e "$full" | grep _NET_WM_WINDOW_TYPE_NORMAL | cut -f2-)"
+    comms="$(echo -e "$normal" | cut -f2 | xargs -I PID ps -o args= -p PID | cut -d' ' -f1 | xargs -I NAME basename NAME  )"
+
+    paste <(echo -e "$normal" | cut -f1) <(echo -e "$comms") <(echo -e "$normal" | cut  -f2-)
+}
+
 case $action in
   help|--help)
     bash_setup print_help $0
@@ -18,13 +43,26 @@ case $action in
 
   "desktop_entries")
     # === desktop_entries  # Returns list of .desktop entries
-    find  \
+    find -L \
       /home/da/.local/share/applications \
       /usr/share/applications/           \
       -ignore_readdir_race -maxdepth 1   \
       -type f                            \
       -iname "*.desktop" | sort
     ;;
+
+  "desktop_exec")
+      path="$1"
+      shift
+
+      # === Example input:
+      #   Exec=/path/cmd --dom=romere
+      raw="$(grep "Exec=" "$path" | cut -d'=' -f2- | head -n 1)"
+      raw="${raw//\'/}"
+      raw="${raw//\\t/ }"
+
+      echo -e "$raw" | sed 's/%.//'
+      ;;
 
   "desktop_entry_to_insert")
     db="$1"
@@ -67,37 +105,52 @@ case $action in
     );"
     ;;
 
+  "app_name_to_win_id")
+    # === app_name_to_win_id  xfce4-terminal
+    # === app_name_to_win_id  nemo
+    # === Get the name from the 2nd column in: normal_window_info
+    app_name_to_win_id $@
+    ;;
+
+
   "activate_or_launch")
     # === activate_or_launch id # activates or launches window
 
-    name="$1"
+    desktop_name="$1"
+    app_name="$1"
     shift
-    case $name in
-      gnome-terminal)
-        name="gnome-terminal-server"
+    case $app_name in
+    gnome-terminal)
+        app_name="gnome-terminal-server"
+        ;;
+    emacsclient)
+        app_name="emacs"
         ;;
     esac
 
-    win_id="$($0 normal_window_info |  grep --extended-regexp -i '^[^[:space:]]+[[:space:]]'$name'[[:space:]]'  | cut -f1 || :)"
+    win_id="$(app_name_to_win_id $app_name)"
     if [[ -n "$win_id" ]]; then
       wmctrl -ia "$win_id"
     else
-      cmd="$(sqlite3 -separator $'\t' "$DB_FILE" "SELECT exec FROM desktops WHERE id = '$name' LIMIT 1;")"
-      if [[ -z "$cmd" ]]; then
-        echo "== Not found: $name" 1>&2
+      desktop="$($0 desktop_entries | grep "/${desktop_name}.desktop")"
+      if [[ -z "$desktop" ]]; then
+        echo "== Not found: $app_name" 1>&2
         exit 1
       fi
+      cmd="$($0 desktop_exec "$desktop")"
+      if [[ -z "$cmd" ]]; then
+        exit 1
+      fi
+
       nohup $cmd &>/dev/null &
-      if [[ "$name" == "xfce4-appfinder" ]]; then
-        COUNTER=0
-        id=""
-        until [[ -n "$id" ]] ||  [[ $COUNTER -eq 10 ]]; do
-          id="$(xwininfo -root -children -tree | { grep appfind || echo ""; } | { grep Application || echo ""; } | tr -s ' ' | cut -d' ' -f2)"
-          COUNTER=$(( $COUNTER + 1 ))
-        done
-        if [[ -n "$id" ]]; then
-          wmctrl -ia "$id"
-        fi
+      COUNTER=0
+      id=""
+      until [[ -n "$id" ]] ||  [[ $COUNTER -eq 10 ]]; do
+        id="$(app_name_to_win_id $app_name)"
+        COUNTER=$(( $COUNTER + 1 ))
+      done
+      if [[ -n "$id" ]]; then
+        wmctrl -ia "$id"
       fi
     fi
     ;;
@@ -145,34 +198,13 @@ case $action in
 
   "normal_window_info")
     # === normal_window_info # Returns a TAB-delimited list: winid exec_name, pid, title
-    info="$(wmctrl -lp | tr -s ' ')"
-    win_ids="$(echo -e "$info" | cut -d' ' -f1)"
-    types="$(echo -e "$win_ids" | xargs -I ID xprop -id ID _NET_WM_WINDOW_TYPE  | cut -d'=' -f2- | tr -d ' ')"
-    pids="$(echo -e "$info" | cut -d' ' -f3)"
-    titles="$(echo -e "$info" | cut -d' ' -f5-)"
+    normal_window_info $@
 
-    full="$(paste <(echo -e "$types") <(echo -e "$win_ids") <(echo -e "$pids") <(echo -e "$titles"))"
 
-    # We first HAVE TO filter out non-normal windows, THEN get the PID/COMM info.
-    # This is because sometimes the pid of window is listed as "0". I don't know why.
-    #  A pid of "0" will lead "ps" to give us an out-of-range error.
-    normal="$(echo -e "$full" | grep _NET_WM_WINDOW_TYPE_NORMAL | cut -f2-)"
-    comms="$(echo -e "$normal" | cut -f2 | xargs -I PID ps -o args= -p PID | cut -d' ' -f1 | xargs -I NAME basename NAME  )"
-
-    # procs=""
-    # while read -r PID; do
-      # temp="$(pstree -An $PID | head -n 10 | tr -d "\n" | tr -s ' ')"
-      # if [[ -z "$procs" ]]; then
-        # procs="$temp"
-      # else
-        # procs="${procs}\n${temp}"
-      # fi
-    # done < <(echo -e "$raw" | tr -s ' ' | cut -d' ' -f3)
-
-    paste <(echo -e "$normal" | cut -f1) <(echo -e "$comms") <(echo -e "$normal" | cut  -f2-)
     ;;
 
   "watch")
+    exit 0
 
     while true; do
       sleep 1
@@ -180,7 +212,6 @@ case $action in
       sleep 30
     done
 
-    exit 0
 
     # === watch
     orig_dir="/apps/gui_setup/tmp"
